name: ShellCheck

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Lint shell scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          additional_files: 'blockchaingather'
